apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
  namespace: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - name: data-api
          image: data-api:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: data-api
  namespace: data-api
spec:
  type: NodePort
  selector:
    app: data-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000